### ISSUE TITLE
Unalbe to bundle domain

### ISSUE THREAD

**Issue by lilytumblr** [strugee/fulldom-server#9]
I am not able to bundle domain.
SSH my machine and input
FULLDOM_ADDRESS=http://myexampledomain.com fulldom-server
It output the following errors
Error: getaddrinfo ENOTFOUND http://myexampledomain.com
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
What am I doing wrong?

**Comment by strugee** [comment]
`FULLDOM_ADDRESS` is the address to listen on, _not_  the URL to crawl. If you provide a domain it will be resolved into an IP address. `http://` isn't part of the domain so don't include it, it will cause resolution to fail.

Please consult the README; it should detail all of this. If there's something that needs to be clarified let me know and I can make that happen.

**Comment by lilytumblr** [comment]
Hi,
This is what i have tried.
 FULLDOM_PORT=8000 FULLDOM_ADDRESS=myexampledomain.com  fulldom-server
and
 FULLDOM_ADDRESS=myexampledomain.com  fulldom-server
It both returns
Error: listen EADDRNOTAVAIL 52.167.6.11:8000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1350:19)
    at listenInCluster (net.js:1408:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1517:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)

I see some port errors and its trying to listen on port 8000. In fact I dont need the port but only an url so i can use it in huginn instead of phantomjscloud. Is the port a must? I also tried different port number but returned the same error.   Is there a way to overwrite the presetting to let it not use the port as it seems that the port caused the error

**Comment by strugee** [comment]
Does your machine have the IP address `52.167.6.11` allocated to it? I think that's likely to be the problem. If you just want to bind the daemon to every IP address available on the system, you could just use the special address `0.0.0.0`.

> Is there a way to overwrite the presetting to let it not use the port as it seems that the port caused the error

I mean, it _has_ to have _some_ port, by definition? This is an HTTP service. "Running HTTP without a port" is nonsensical.

Maybe I'm misunderstanding what you're asking? `http://example.com`, by the way, still has a port. It's just implied that it's port 80.

**Comment by lilytumblr** [comment]
alright...
Yes. This is the ip address of the machine where i deploy fulldom code.
I tried also to add the default port 80 just now
FULLDOM_PORT=80 FULLDOM_ADDRESS=myowndomain.com fulldom-server
Still same error.  The machine is azure virtual machine ubuntu. In its portal, i even added 80, 8000, etc port number to the Inbound port rules and Outbound port rules, but not sure if its related.

**Comment by lilytumblr** [comment]
Thank you so much.
After typing 
FULLDOM_PORT=8000 FULLDOM_ADDRESS=0.0.0.0 fulldom-server, it finally works. But not with other port number😄

**Comment by strugee** [comment]
Sure thing.

Ports <1024 require you to be root. Probably that's what you were running into. See #4.

Possibly what happened is that Azure assigned a public IP address and your machine got a private address. You could check the IP address that is _actually_ allocated to the machine (as opposed to what it seems to be publicly) with `ip addr`.

**Comment by strugee** [comment]
Closing due to inactivity. @lilytumblr, let me know if you need this reopened.
